# Generated by Django 5.2.5 on 2025-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttag_productmodel_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
