# Generated by Django 5.2.5 on 2025-09-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='products.productcategory'),
        ),
    ]
