# Generated by Django 5.2.5 on 2025-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='short_description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
