# Generated by Django 5.2.5 on 2025-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productmodel_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='sizes',
        ),
        migrations.AddField(
            model_name='productquantity',
            name='colors',
            field=models.ManyToManyField(related_name='products_quantity', to='products.productcolor'),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='sizes',
            field=models.ManyToManyField(related_name='products_quantity', to='products.productsize'),
        ),
    ]
