# Generated by Django 5.2.5 on 2025-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productquantity_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('deleted', 'Deleted')], default='published', max_length=10),
        ),
    ]
