# Generated by Django 5.2.5 on 2025-09-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.RenameModel(
            old_name='TagModel',
            new_name='CategoriesModel',
        ),
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='CommentsModel',
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='TagsModel',
        ),
        migrations.AlterModelOptions(
            name='categoriesmodel',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tagsmodel',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='BlogsModel',
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.authorsmodel'),
        ),
    ]
