# Generated by Django 5.2.5 on 2025-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_authorsmodel_rename_tagmodel_categoriesmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='category',
            field=models.ManyToManyField(related_name='blogs', to='blogs.categoriesmodel'),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='tag',
            field=models.ManyToManyField(related_name='blogs', to='blogs.tagsmodel'),
        ),
    ]
