# Generated by Django 5.2.5 on 2025-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogsmodel_category_alter_blogsmodel_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsmodel',
            name='profession',
            field=models.CharField(default='Unknown', max_length=128),
            preserve_default=False,
        ),
    ]
