# Generated by Django 5.2.5 on 2025-09-02 08:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_authorsmodel_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
