# Generated by Django 5.2.5 on 2025-09-09 13:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsmodel',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authorsmodel',
            name='bio_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authorsmodel',
            name='profession_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='authorsmodel',
            name='profession_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='blogsmodel',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blogsmodel',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blogsmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogsmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
