# Generated by Django 5.2.5 on 2025-09-09 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_authorsmodel_bio_en_authorsmodel_bio_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesmodel',
            options={'verbose_name': 'blogs category', 'verbose_name_plural': 'blogs categories'},
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='blogs.categoriesmodel'),
        ),
        migrations.AlterField(
            model_name='categoriesmodel',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='categoriesmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='categoriesmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
