# Generated by Django 5.2.5 on 2025-10-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blogsmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('deleted', 'Deleted')], default='published', max_length=10),
        ),
    ]
