# Generated by Django 5.2.5 on 2025-10-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blogsmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='website',
        ),
    ]
